This implements a test for RPC on Zenoh transport.
eclipse-uprotocol/up-transport-zenoh-cpp pull request #89
Opened 2024-08-06 17:16 UTC by debruce

This test is not currently working. This is simply to put the code up for review. The test is one process with one transport handle handling both the client and server callbacks. The server callback is invoked, but the client handler is not. This PR contains two other 'tests' as standalone programs meant to exercise client and server separately. This is unsuitable for test automation, but it demonstrates the fact that there are other problems. In that case, the server callback is not found though communication to the server is evident. The client callback is invoked, but with the information that the server side lookup failed.

2024-08-06 17:18 UTC, gregmedd requested changes

2024-08-06 17:18 UTC, gregmedd commented on test/extra/RpcClientOnlyTest.cpp
Remove this test from the PR. It was not requested as part of this task

2024-08-06 17:18 UTC, gregmedd commented on test/extra/RpcServerOnlyTest.cpp
Remove this file from the PR. It was not requested as part of this task.

2024-08-06 18:45 UTC, gregmedd commented
@debruce - this test appears to be passing. Can you clean up the commit message and fix the lint issue?

2024-08-06 18:57 UTC, gregmedd reviewed
Some cleanup required in the test. Make sure unnecessary commented code and logging is removed. Also verify all the necessary assertions are in place.

2024-08-06 18:57 UTC, gregmedd commented on test/extra/RpcClientServerTest.cpp
> +// #include <google/protobuf/util/message_differencer.h>
Minor: remove unused code

2024-08-06 18:57 UTC, gregmedd commented on test/extra/RpcClientServerTest.cpp
> +constexpr std::string_view TOPIC_URI_STR = "//test0/10001/1/8000";
Are these unused?

2024-08-06 18:57 UTC, gregmedd commented on test/extra/RpcClientServerTest.cpp
> +	cout << makeUUri(ENTITY_URI_STR).ShortDebugString() << endl;
Is this logging necessary?

2024-08-06 18:57 UTC, gregmedd commented on test/extra/RpcClientServerTest.cpp
> +		    // EXPECT_TRUE(maybe_response);
Shouldn't this check be included?

2024-08-06 18:57 UTC, gregmedd commented on test/extra/RpcClientServerTest.cpp
> +TEST_F(RpcClientServerTest, SomeTestName)
Remove TODO and give the test case a name

2024-08-07 19:36 UTC, gregmedd approved these changes
Looks like a good start to RPC tests

2024-08-07 19:42 UTC, gregmedd commented
We believe the failure of this test case is caused by a bug in the zenoh transport implementation. We can move forward with merging this test. Bug fix will follow in a future PR.

2024-08-08 19:40 UTC, billpittman approved these changes
One minor nitpick is all.

2024-08-08 19:40 UTC, billpittman commented on test/extra/RpcClientServerTest.cpp
> +	MyUUri ident_{"me_authority", 65538, 1, 0};
Nitpick (sorta) - Can you change the ue_id and resource_id to hexadecimal please.  I think its easier to read that way and easier to see high/low bits that way.

2024-08-08 19:42 UTC, billpittman commented
> We believe the failure of this test case is caused by a bug in the zenoh transport implementation. We can move forward with merging this test. Bug fix will follow in a future PR.

Are we able to skip this test for the near future, just so we don't get PR's hung up with falsely failing tests ?

2024-08-08 21:01 UTC, gregmedd commented
> > We believe the failure of this test case is caused by a bug in the zenoh transport implementation. We can move forward with merging this test. Bug fix will follow in a future PR.
> 
> Are we able to skip this test for the near future, just so we don't get PR's hung up with falsely failing tests ?

I recently made a change to allow non-passing tests in PRs in order to allow work to proceed until various bugs are fixed. It's still in place currently, which is why this PR could be merged now. Once the issues are fixed, I plan on rolling back that change.

2024-08-09 18:34 UTC, merged